version: '3'
services:
    mongo:
      hostname: mongo
      container_name: mongo
      image: mongo
      expose:
        - 27017
      ports:
        - '27017:27017'
      restart: always
      entrypoint:
        - mongod
        - '--bind_ip_all'
        - '--port'
        - '27017'